name: Build QuoteWidget APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (repo may be empty)
        uses: actions/checkout@v4

      - name: Generate Android project files
        run: |
          set -e

          mkdir -p app/src/main/java/com/example/quotewidget
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values
          mkdir -p app/src/main/res/xml
          mkdir -p app/src/main/res/drawable
          mkdir -p app/src/main/res/mipmap-anydpi-v26

          cat > settings.gradle <<'EOF'
          pluginManagement {
              repositories {
                  google()
                  mavenCentral()
                  gradlePluginPortal()
              }
          }

          dependencyResolutionManagement {
              repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
              repositories {
                  google()
                  mavenCentral()
              }
          }

          rootProject.name = "QuoteWidget"
          include(":app")
          EOF

          cat > build.gradle.kts <<'EOF'
          plugins {
              id("com.android.application") version "8.6.0" apply false
              id("org.jetbrains.kotlin.android") version "2.0.20" apply false
          }
          EOF

          cat > app/build.gradle.kts <<'EOF'
          plugins {
              id("com.android.application")
              id("org.jetbrains.kotlin.android")
          }

          android {
              namespace = "com.example.quotewidget"
              compileSdk = 35

              defaultConfig {
                  applicationId = "com.example.quotewidget"
                  minSdk = 24
                  targetSdk = 35
                  versionCode = 1
                  versionName = "1.0"
                  vectorDrawables.useSupportLibrary = true
              }

              buildTypes {
                  release {
                      isMinifyEnabled = true
                      proguardFiles(
                          getDefaultProguardFile("proguard-android-optimize.txt"),
                          "proguard-rules.pro"
                      )
                  }
                  debug { isMinifyEnabled = false }
              }

              compileOptions {
                  sourceCompatibility = JavaVersion.VERSION_17
                  targetCompatibility = JavaVersion.VERSION_17
              }
              kotlinOptions { jvmTarget = "17" }
              buildFeatures { viewBinding = true }
          }

          dependencies {
              implementation("androidx.core:core-ktx:1.13.1")
              implementation("androidx.appcompat:appcompat:1.7.0")
              implementation("com.google.android.material:material:1.12.0")
              implementation("androidx.activity:activity-ktx:1.9.3")
              implementation("androidx.constraintlayout:constraintlayout:2.2.0")
          }
          EOF

          : > app/proguard-rules.pro

          cat > app/src/main/AndroidManifest.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">

              <application
                  android:allowBackup="true"
                  android:label="QuoteWidget"
                  android:icon="@mipmap/ic_launcher"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.QuoteWidget">

                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>

                  <receiver
                      android:name=".QuoteWidgetProvider"
                      android:exported="false"
                      android:label="Quote Widget">
                      <intent-filter>
                          <action android:name="android.appwidget.action.APPWIDGET_UPDATE" />
                      </intent-filter>
                      <meta-data
                          android:name="android.appwidget.provider"
                          android:resource="@xml/quote_appwidget_info" />
                  </receiver>

              </application>
          </manifest>
          EOF

          cat > app/src/main/java/com/example/quotewidget/Prefs.kt <<'EOF'
          package com.example.quotewidget

          import android.content.Context
          import android.content.SharedPreferences

          private const val PREF_NAME = "quote_prefs"
          private const val KEY_TEXT = "widget_text"

          object Prefs {
              private fun prefs(ctx: Context): SharedPreferences =
            
